ALTER TABLE employee
ADD CONSTRAINT fk_department_id
FOREIGN KEY (DEPARTMENT_ID)  REFERENCES department(ID) ON DELETE SET NULL;

ALTER TABLE employee_role
ADD CONSTRAINT fk_employee_login
FOREIGN KEY (EMPLOYEE_LOGIN) REFERENCES employee(LOGIN);