CREATE TABLE EMPLOYEE
(
    LOGIN         VARCHAR(255) NOT NULL,
    PASSWORD      VARCHAR(255),
    FIRST_NAME    VARCHAR(255),
    LAST_NAME     VARCHAR(255),
    BIRTH_DATE    DATE,
    DEPARTMENT_ID BINARY(16),
    PRIMARY KEY (LOGIN)
);
