version: '3.8'
services:

  employee-service:
    build:
      dockerfile: Dockerfile
      context: employee-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-employee:3306/employees?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mmx31sse

    ports:
    - '8081:8080'

  tgbot-service:
    build:
      dockerfile: Dockerfile
      context: tgbot-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-tgbot:3306/tgbot?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mmx31sse

  mysql-employee:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mmx31sse
      MYSQL_DATABASE: employee
    ports:
      - '8085:3306'

  mysql-tgbot:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mmx31sse
      MYSQL_DATABASE: tgbot
    ports:
      - '8086:3306'