bot:
  name: CompanyEmployerBot
  token: 7244519908:AAHY8ZBhMN-CYlgQCAJBujnoetGlrYrptYk
  invite-link: https://t.me/+li1J8FDF3VJhZTAy
  company-chat-id: -1002221380356


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tgbot
    username: root
    password: mmx31sse
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true


feign:
  employee-service:
    url: http://localhost:8081
  username: admin
  password: admin

job:
  cron: 0 */1 * * * *
