spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees
    username: root
    password: mmx31sse

  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

  application:
    name: employee-service

server:
  port: 8081


