CREATE TABLE USERS
(
    CHAT_ID       BIGINT,
    USERNAME      VARCHAR(255) NOT NULL,
    FIRST_NAME    VARCHAR(255) NOT NULL,
    LAST_NAME     VARCHAR(255) NOT NULL,
    LOGIN         VARCHAR(255) NOT NULL,
    PRIMARY KEY (CHAT_ID)
);
