CREATE TABLE users
(
    ID            BIGINT NOT NULL,
    CHAT_ID       BIGINT NOT NULL,
    USERNAME      VARCHAR(255),
    FIRST_NAME    VARCHAR(255),
    LAST_NAME     VARCHAR(255),
    LOGIN         VARCHAR(255),
    PRIMARY KEY (ID)
);
